### ISSUE TITLE
Support Tripple-Slash directive in .ts files.

### ISSUE THREAD

**Issue by SantoJambit** [FlorianRappl/dets#14]
From within a .d.ts file, you can use the tripple-slash directive to import other .d.ts files and even normal .ts files.

When you try it the other way though it doesn't work. Importing .d.ts files via tripple-slash directive from a normal .ts file runs without errors, but the content of the .d.ts file will not be included in the result.

**Comment by SantoJambit** [comment]
Correction: It seems, that the tripple slash directive itself works, but if the referenced file is a d.ts file it will be ignored

**Comment by FlorianRappl** [comment]
> Correction: It seems, that the tripple slash directive itself works, but if the referenced file is a d.ts file it will be ignored

In any case I'd investigate / improve this.

**Comment by SantoJambit** [comment]
My use-case is, that I want to have statements like this in the final d.ts file:

```typescript
declare module '*.png' {
    const content: string;
    export default content;
}
```

Using a tripple-slash directive for this does not work. I can't "use" these either (afaik), so they will never be exported.

So what would be the best way to achieve this?

**Comment by FlorianRappl** [comment]
> So what would be the best way to achieve this?

It depends - if that goes into Piral direction I would really just copy these files (or the file, should be just a single one) as a workaround.

In dets I think it should be possible, too. Only question is if you'd need to do something. It should be automatically used as an ambient module definition.

I'll check if we somehow can find / use these and what would need to be done, e.g., if you'd need to use a png as module (following the example above) for it to be recognized.
