### ISSUE TITLE
Support JSDoc tags in the generated declaration file

### ISSUE THREAD

**Issue by Robbson** [FlorianRappl/dets#19]
We should provide support for JSDoc tags in addition to the already supported comment lines in the generated .d.ts file.

This way an API consumer gets all available documentation like parameter descriptions, examples, deprecation warnings etc.

**Comment by Robbson** [comment]
#20

**Comment by FlorianRappl** [comment]
Landed in `develop` and the preview (of 0.8.0).

Thanks for the outstanding contribution @Robbson ! :beers:
