### ISSUE TITLE
reexporting a default function turns into const with type any

### ISSUE THREAD

**Issue by SantoJambit** [FlorianRappl/dets#2]
# Bug Report

Moved from Piral.

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version?
- [x] Did you perform a search in the issues?

## Environment Details and Version

piral 0.10.9

## Description

When you default export a function, then **export this in a named fashion** in your exports.ts file, it becomes a const with type any.

## Steps to Reproduce

1. first.ts: export default function
2. second.ts: import default under a name
3. second.ts: export the now named function
4. api.ts

## Expected behavior

Should export the function type

## Actual behavior

Exports a const with type any.

## Possible Origin / Solution

See the MWE: https://github.com/SantoJambit/shell-mwe/commit/b534b409730ba00bded5b6ee504f97b8910a2eb9

**Comment by FlorianRappl** [comment]
A failing (isolated) test would be appreciated. Thanks!

**Comment by SantoJambit** [comment]
Created a PR with a failing test
