### ISSUE TITLE
JSDoc in nested object not being exportet

### ISSUE THREAD

**Issue by SantoJambit** [FlorianRappl/dets#21]
This is happening in piral 0.12.4, which uses dets 0.9.2:

```typescript
/**
 * Object description
 * @see exampleExport2
 */
export const exampleExport = {
    /**
     * Some description
     * @param key some param
     */
    start(key: string) {
        return key;
    },
};
```

Output:
```typescript
  /**
   * Object description
   * @see exampleExport2
   */
  export const exampleExport: {
    start(key: string): string;
  };
```

I saw some work was done in #19, but this seems to be a special case that slipped through the tests.

**Comment by FlorianRappl** [comment]
Yeah good point. Its not too late for a 0.9.3 that goes into Piral 1.0.

Let me see how quickly that can be done.

Thanks!

**Comment by FlorianRappl** [comment]
Fix landed in `develop`. 0.9.3 about to be released.
