### ISSUE TITLE
Cannot read property 'symbol' of undefined

### ISSUE THREAD

**Issue by carvinlo** [FlorianRappl/dets#23]
When [symbol is undefined](https://github.com/FlorianRappl/dets/blob/dd8818f2ccc4b6095d6a7e3f0491a3424b30125c/src/helpers/node.ts#L43), I get an error:
`Cannot read property 'symbol' of undefined`

I tried to [fix it](https://github.com/FlorianRappl/dets/compare/develop...carvinlo:patch-1) and the error did not appear. Is it correct to remove those cluses whose symbol is undefined?

**Comment by FlorianRappl** [comment]
I think this is totally okay and the fix would be an appreciated PR!

Thanks for bringing this up @carvinlo ! :beers:
