### ISSUE TITLE
--module-declaration arg is not passed to `generateDeclaration`.

### ISSUE THREAD

**Issue by michalkvasnicak** [FlorianRappl/dets#42]
I noticed that the `--module-declaration` arg is not passed to `generateDeclaration`. Because of that, using `--no-module-declaration` doesn't work to disable `declare module ...`.

Workaround for now is to use programatic api and write your own script so you can pass `noModuleDeclaration: false`.

**Comment by FlorianRappl** [comment]
Good catch - thanks. You want to do a PR?

Otherwise I'd take care of it later.

**Comment by FlorianRappl** [comment]
Is fixed in the preview and will be out with 0.16.
