### ISSUE TITLE
Dets does not import declaration files?

### ISSUE THREAD

**Issue by wiresnchains** [FlorianRappl/dets#45]
I may be doing something wrong here, however my declaration file for Utility interfaces and types does not include correctly when using dets.
Here is my declaration file which is referenced in the tsconfig.json (thus not imported by the typescript files using import keyword)
```ts
declare interface WaveDictionary<T> {
    [key: string]: T;
}

declare type WaveDataType = string | number | boolean;
declare type WaveProxyHandler = (newValue: any) => Promise<boolean>;
declare type WaveLogicalOperatorHandler = (data: any, compareWith: any) => boolean;
```
And these interfaces and types are not being imported into the dets out file when building (The .d.ts file is withing the --files parameter scope)
Here is my cli command:
```sh
dets src/index.ts --name @wave-frontend/wave-js --files src/**/*.ts --out dist/index.d.ts
```
The `@types` folder is located in the src folder so it should be picked up if I am not missing something

**Comment by FlorianRappl** [comment]
Hm we pretty much hand over the files to TypeScript. So we'd need to check how TypeScript handles those - and what might be the difference.

**Comment by wiresnchains** [comment]
I did manage to come up with a solution using `export` keyword instead of `declare`

**Comment by FlorianRappl** [comment]
OK - I mean also in a `d.ts` you are supposed to export the things you want to use outside of it. The exception is that a `d.ts` file might contain module declarations.

To me it sounds like the `d.ts` might not have been sound (i.e., would it have worked in general?).
